### ISSUE TITLE
Ghost feature does not support .dz files

### ISSUE THREAD

**Issue by m-e-l-b-o** [j0zzz/JoeQuake#52]

**Comment by Flecked42** [comment]
I don't really see this as an issue tbh, unless its something that can be easily changed.

**Comment by matthewearl** [comment]
I think we can do this but it is not completely trivial.  The tricky bit is deleting the extracted dem file when we're done. In the case where we concurrently `playdemo` the same demo that we're ghosting, we need to be careful to only delete the extracted file when everyone is done with it.   With the ghost feature, we'd likely want to keep the dem file around from `ghost` command to `ghost_remove` to avoid having to decompress every map load.  This means that we'd need to handle this concurrency issue when someone loads the ghost, and then plays the same demo, which I can imagine happening frequently.

Having thought about it a bit, I think the easiest and cleanest way to deal with this would be to create a temp dir each time the dzip process is invoked, with the contents being placed in that temp dir.  For example, `<game_dir>/dzip_temp/<uuid>/e1m1_019.dem`.  This makes cleanup easier too, since we just need to recursively rm the temp dir.  The idea is we'd start a new dzip process, and therefore create a new directory, every time either `playdemo` or `ghost` is run, with cleanup happening when either the demo stops or `ghost_remove` occurs.

Can you see any problems with this approach, @j0zzz @kugelrund ?  Can you see an obvious solution which I've missed?

**Comment by j0zzz** [comment]
Why not extract the demo only once when it was added to the ghost list? And delete it, when
 - the ghost is removed
 - OR the game quits
And I would try to clean the temp folder anyways when a new ghost is added (for the case if the game crashed and extracted unneded dem files remained in the temp)

The whole process would be reworked though when the ghost list would contain more than 1 items in the future

**Comment by matthewearl** [comment]
That would work, as long as the `playdemo` extract dir is isolated from the `ghost` extract dir.  If there's a clean way to share the extracting code (ie. the funcs to initiate the extract, the poll for the func being finished, and the cleanup func) this is probably the simplest way to fix this.

**Comment by matthewearl** [comment]
I'm having a go at fixing this, will make a PR if I get it working.

**Comment by j0zzz** [comment]
Great, thanks a lot Matt.

**Comment by j0zzz** [comment]
Fixed by merging PR #60
